### ISSUE TITLE
add InsertManifest API

### ISSUE THREAD

**Issue by cachalots** [everFinance/arseeding#48]
https://github.com/everFinance/arseeding/blob/95fb42f72cb3b7bbca3e65462937fefe540f31cf/api.go#L79
At present, only call this API to passive insert manifest.  I hope to have a API for active insert.

**Comment by zyjblockchain** [comment]
https://github.com/everFinance/arseeding/pull/49
This pr implements this function

**Comment by cachalots** [comment]
#50 insert manifest when syncing task can reduce my dep on this API
