### ISSUE TITLE
Importing GenApi leads to Type Error.

### ISSUE THREAD

**Issue by Roaring30s** [everFinance/arseeding#60]
When calling this code:
```
import { genAPI } from 'arseeding-js'
const instance = await genAPI(window.ethereum)
```
I am getting this error: 
```
Uncaught TypeError: Cannot convert a BigInt value to a number
```

**Comment by charles-lpd** [comment]
> 调用此代号时：
> 
> ```
> import { genAPI } from 'arseeding-js'
> const instance = await genAPI(window.ethereum)
> ```
> 
> 我收到这个错误：
> 
> ```
> Uncaught TypeError: Cannot convert a BigInt value to a number
> ```

Have you solved it now?
Can you describe the usage and error messages carefully so that can troubleshoot them?

**Comment by charles-lpd** [comment]
https://www.notion.so/permadao/genAPi-Err-Uncaught-TypeError-Cannot-convert-a-BigInt-value-to-a-number-14a632938fc349e99387e9b43d90c8cf

Not sure if this article will solve your problem?
